[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
gas_reports = []
fs_permissions = [{ access = "read", path = "./broadcast" }]

[rpc_endpoints]
base-mainnet = "https://mainnet.base.org"
base-testnet = "https://sepolia.base.org"
local = "127.0.0.1:8545"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
