import {
  ArrowDown,
  ArrowUp,
  Calendar,
  CaretDown,
  Coins,
  CoinVertical,
  Clock,
  Check,
  CircleNotch,
  CurrencyDollar,
  FileText,
  Gear,
  Info,
  ThumbsUp,
  ThumbsDown,
  Timer,
  Trash,
  User,
  Wallet,
  Warning,
  X,
} from "@phosphor-icons/react/dist/ssr";

export const Icons = {
  arrowdown: ArrowDown,
  arrowup: ArrowUp,
  calendar: Calendar,
  caretdown: CaretDown,
  coin: CoinVertical,
  coins: Coins,
  clock: Clock,
  close: X,
  check: Check,
  currency: CurrencyDollar,
  help: Info,
  post: FileText,
  user: User,
  settings: Gear,
  spinner: CircleNotch,
  timer: Timer,
  thumbsdown: ThumbsDown,
  thumbsup: ThumbsUp,
  trash: Trash,
  warning: Warning,
  wallet: Wallet,
};
